// Generated by gencpp from file chisel_msgs/GetAllChunksService.msg
// DO NOT EDIT!


#ifndef CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICE_H
#define CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICE_H

#include <ros/service_traits.h>


#include <chisel_msgs/GetAllChunksServiceRequest.h>
#include <chisel_msgs/GetAllChunksServiceResponse.h>


namespace chisel_msgs
{

struct GetAllChunksService
{

typedef GetAllChunksServiceRequest Request;
typedef GetAllChunksServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAllChunksService
} // namespace chisel_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chisel_msgs::GetAllChunksService > {
  static const char* value()
  {
    return "1ed132c081b5f4f409c36677e0cb6ee0";
  }

  static const char* value(const ::chisel_msgs::GetAllChunksService&) { return value(); }
};

template<>
struct DataType< ::chisel_msgs::GetAllChunksService > {
  static const char* value()
  {
    return "chisel_msgs/GetAllChunksService";
  }

  static const char* value(const ::chisel_msgs::GetAllChunksService&) { return value(); }
};


// service_traits::MD5Sum< ::chisel_msgs::GetAllChunksServiceRequest> should match 
// service_traits::MD5Sum< ::chisel_msgs::GetAllChunksService > 
template<>
struct MD5Sum< ::chisel_msgs::GetAllChunksServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chisel_msgs::GetAllChunksService >::value();
  }
  static const char* value(const ::chisel_msgs::GetAllChunksServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chisel_msgs::GetAllChunksServiceRequest> should match 
// service_traits::DataType< ::chisel_msgs::GetAllChunksService > 
template<>
struct DataType< ::chisel_msgs::GetAllChunksServiceRequest>
{
  static const char* value()
  {
    return DataType< ::chisel_msgs::GetAllChunksService >::value();
  }
  static const char* value(const ::chisel_msgs::GetAllChunksServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chisel_msgs::GetAllChunksServiceResponse> should match 
// service_traits::MD5Sum< ::chisel_msgs::GetAllChunksService > 
template<>
struct MD5Sum< ::chisel_msgs::GetAllChunksServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chisel_msgs::GetAllChunksService >::value();
  }
  static const char* value(const ::chisel_msgs::GetAllChunksServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chisel_msgs::GetAllChunksServiceResponse> should match 
// service_traits::DataType< ::chisel_msgs::GetAllChunksService > 
template<>
struct DataType< ::chisel_msgs::GetAllChunksServiceResponse>
{
  static const char* value()
  {
    return DataType< ::chisel_msgs::GetAllChunksService >::value();
  }
  static const char* value(const ::chisel_msgs::GetAllChunksServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICE_H
