// Generated by gencpp from file chisel_msgs/GetAllChunksServiceResponse.msg
// DO NOT EDIT!


#ifndef CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICERESPONSE_H
#define CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <chisel_msgs/ChunkListMessage.h>

namespace chisel_msgs
{
template <class ContainerAllocator>
struct GetAllChunksServiceResponse_
{
  typedef GetAllChunksServiceResponse_<ContainerAllocator> Type;

  GetAllChunksServiceResponse_()
    : chunks()  {
    }
  GetAllChunksServiceResponse_(const ContainerAllocator& _alloc)
    : chunks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::chisel_msgs::ChunkListMessage_<ContainerAllocator>  _chunks_type;
  _chunks_type chunks;





  typedef boost::shared_ptr< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAllChunksServiceResponse_

typedef ::chisel_msgs::GetAllChunksServiceResponse_<std::allocator<void> > GetAllChunksServiceResponse;

typedef boost::shared_ptr< ::chisel_msgs::GetAllChunksServiceResponse > GetAllChunksServiceResponsePtr;
typedef boost::shared_ptr< ::chisel_msgs::GetAllChunksServiceResponse const> GetAllChunksServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chisel_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chisel_msgs': ['/home/sheldonmao/catkin_ws/src/chisel_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ed132c081b5f4f409c36677e0cb6ee0";
  }

  static const char* value(const ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ed132c081b5f4f4ULL;
  static const uint64_t static_value2 = 0x09c36677e0cb6ee0ULL;
};

template<class ContainerAllocator>
struct DataType< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chisel_msgs/GetAllChunksServiceResponse";
  }

  static const char* value(const ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ChunkListMessage chunks\n\
\n\
\n\
\n\
================================================================================\n\
MSG: chisel_msgs/ChunkListMessage\n\
Header header\n\
ChunkMessage[] chunks\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: chisel_msgs/ChunkMessage\n\
Header header\n\
\n\
#Chunk ID spatial position\n\
int32 ID_x\n\
int32 ID_y\n\
int32 ID_z\n\
\n\
#Chunk spatial hash value\n\
int64 spatial_hash\n\
\n\
#Size of a voxel in meters\n\
float32 resolution_meters\n\
\n\
#number of voxels in each dimension\n\
int32 num_voxels_x\n\
int32 num_voxels_y\n\
int32 num_voxels_z\n\
\n\
#Binary serialization of distances/weights\n\
uint32[] distance_data\n\
\n\
#Binary serialization of colors/weights\n\
uint32[] color_data\n\
";
  }

  static const char* value(const ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chunks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAllChunksServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chisel_msgs::GetAllChunksServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "chunks: ";
    s << std::endl;
    Printer< ::chisel_msgs::ChunkListMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.chunks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHISEL_MSGS_MESSAGE_GETALLCHUNKSSERVICERESPONSE_H
