// Generated by gencpp from file chisel_msgs/PauseService.msg
// DO NOT EDIT!


#ifndef CHISEL_MSGS_MESSAGE_PAUSESERVICE_H
#define CHISEL_MSGS_MESSAGE_PAUSESERVICE_H

#include <ros/service_traits.h>


#include <chisel_msgs/PauseServiceRequest.h>
#include <chisel_msgs/PauseServiceResponse.h>


namespace chisel_msgs
{

struct PauseService
{

typedef PauseServiceRequest Request;
typedef PauseServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PauseService
} // namespace chisel_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chisel_msgs::PauseService > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chisel_msgs::PauseService&) { return value(); }
};

template<>
struct DataType< ::chisel_msgs::PauseService > {
  static const char* value()
  {
    return "chisel_msgs/PauseService";
  }

  static const char* value(const ::chisel_msgs::PauseService&) { return value(); }
};


// service_traits::MD5Sum< ::chisel_msgs::PauseServiceRequest> should match 
// service_traits::MD5Sum< ::chisel_msgs::PauseService > 
template<>
struct MD5Sum< ::chisel_msgs::PauseServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chisel_msgs::PauseService >::value();
  }
  static const char* value(const ::chisel_msgs::PauseServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chisel_msgs::PauseServiceRequest> should match 
// service_traits::DataType< ::chisel_msgs::PauseService > 
template<>
struct DataType< ::chisel_msgs::PauseServiceRequest>
{
  static const char* value()
  {
    return DataType< ::chisel_msgs::PauseService >::value();
  }
  static const char* value(const ::chisel_msgs::PauseServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chisel_msgs::PauseServiceResponse> should match 
// service_traits::MD5Sum< ::chisel_msgs::PauseService > 
template<>
struct MD5Sum< ::chisel_msgs::PauseServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chisel_msgs::PauseService >::value();
  }
  static const char* value(const ::chisel_msgs::PauseServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chisel_msgs::PauseServiceResponse> should match 
// service_traits::DataType< ::chisel_msgs::PauseService > 
template<>
struct DataType< ::chisel_msgs::PauseServiceResponse>
{
  static const char* value()
  {
    return DataType< ::chisel_msgs::PauseService >::value();
  }
  static const char* value(const ::chisel_msgs::PauseServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHISEL_MSGS_MESSAGE_PAUSESERVICE_H
