// Generated by gencpp from file chisel_msgs/SaveMeshServiceRequest.msg
// DO NOT EDIT!


#ifndef CHISEL_MSGS_MESSAGE_SAVEMESHSERVICEREQUEST_H
#define CHISEL_MSGS_MESSAGE_SAVEMESHSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chisel_msgs
{
template <class ContainerAllocator>
struct SaveMeshServiceRequest_
{
  typedef SaveMeshServiceRequest_<ContainerAllocator> Type;

  SaveMeshServiceRequest_()
    : file_name()  {
    }
  SaveMeshServiceRequest_(const ContainerAllocator& _alloc)
    : file_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMeshServiceRequest_

typedef ::chisel_msgs::SaveMeshServiceRequest_<std::allocator<void> > SaveMeshServiceRequest;

typedef boost::shared_ptr< ::chisel_msgs::SaveMeshServiceRequest > SaveMeshServiceRequestPtr;
typedef boost::shared_ptr< ::chisel_msgs::SaveMeshServiceRequest const> SaveMeshServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chisel_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chisel_msgs': ['/home/sheldonmao/catkin_ws/src/chisel_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2415261c9605b9f38867ffbbe495fc04";
  }

  static const char* value(const ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2415261c9605b9f3ULL;
  static const uint64_t static_value2 = 0x8867ffbbe495fc04ULL;
};

template<class ContainerAllocator>
struct DataType< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chisel_msgs/SaveMeshServiceRequest";
  }

  static const char* value(const ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string file_name\n\
";
  }

  static const char* value(const ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMeshServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chisel_msgs::SaveMeshServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHISEL_MSGS_MESSAGE_SAVEMESHSERVICEREQUEST_H
