(cl:defpackage chisel_msgs-srv
  (:use )
  (:export
   "GETALLCHUNKSSERVICE"
   "<GETALLCHUNKSSERVICE-REQUEST>"
   "GETALLCHUNKSSERVICE-REQUEST"
   "<GETALLCHUNKSSERVICE-RESPONSE>"
   "GETALLCHUNKSSERVICE-RESPONSE"
   "PAUSESERVICE"
   "<PAUSESERVICE-REQUEST>"
   "PAUSESERVICE-REQUEST"
   "<PAUSESERVICE-RESPONSE>"
   "PAUSESERVICE-RESPONSE"
   "RESETSERVICE"
   "<RESETSERVICE-REQUEST>"
   "RESETSERVICE-REQUEST"
   "<RESETSERVICE-RESPONSE>"
   "RESETSERVICE-RESPONSE"
   "SAVEMESHSERVICE"
   "<SAVEMESHSERVICE-REQUEST>"
   "SAVEMESHSERVICE-REQUEST"
   "<SAVEMESHSERVICE-RESPONSE>"
   "SAVEMESHSERVICE-RESPONSE"
  ))

